[package]
name = "coding-interview"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.12.11" ,features = ["blocking"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.134"
tokio = "1.42.0"

